Add helper-guidance
discord-math/discord-math.github.io pull request #6
Opened 2022-12-06 02:14 UTC by jkynaston

2022-12-06 02:19 UTC, mniip requested changes

2022-12-06 02:19 UTC, mniip commented on _config.yml
> +plugins: []
pls fix newline

2022-12-06 02:19 UTC, mniip commented on helper-guidance.md
> +Unfortunately, there are occasions where users come to the server with the sole intent of causing problems, stirring up trouble, or otherwise trolling. While most bad behavior can be safely ignored,
#rules could link to `/rules` instead (probably not `target="blank" in that case).

Discord Terms of Service should not be `.mention`.

2022-12-06 02:32 UTC, mniip approved these changes
LGTM on the technical side

2022-12-06 23:24 UTC, riemann-discord commented on helper-guidance.md
> +While it is not against server rules to use bad language, it may sometimes be frustrating to see. Remember that we are here to discuss and learn mathematics, not to correct eachother's words and use
each other's

2022-12-06 23:26 UTC, riemann-discord commented on helper-guidance.md
> +There are times where, despite your best efforts, a troublesome user will continue to cause issues. In cases like this, it is often best for everyone involved that you take a step back and remove you
In cases like these*

2022-12-07 00:35 UTC, riemann-discord approved these changes

2022-12-21 22:29 UTC, merged